language: python
sudo: false
matrix:
  include:
    - python: 3.6.7
  fast_finish: true
addons:
  apt:
    packages:
      - libxmlsec1-dev
      - swig
install:
  - pip install -r requiremt.txt
script:
  - tox
